/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/test.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
        position={[-0.31, 0.292, -0.118]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.125, 0.125, 0.125]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.head_lowPolyTest.geometry}
        material={materials.defaultMat}
        position={[-0.014, -0.063, -0.475]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[8.874, 8.874, 8.874]}
      />
    </group>
  );
}

useGLTF.preload("/test.gltf");
